#!/bin/bash
#
# Daily Scheduler - Silver Tier
# ==============================
# Runs daily at 8AM to generate summary from /Done files
#
# Usage: ./daily_scheduler.sh
#
# Setup (Linux/Mac):
# ------------------
# 1. Make executable: chmod +x daily_scheduler.sh
# 2. Edit crontab: crontab -e
# 3. Add line: 0 8 * * * /full/path/to/daily_scheduler.sh
#
# Test manually: ./daily_scheduler.sh

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DONE_DIR="$PROJECT_ROOT/Done"
LOGS_DIR="$PROJECT_ROOT/Logs"
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
SUMMARY_FILE="$LOGS_DIR/daily_summary_$DATE.md"

# Ensure logs directory exists
mkdir -p "$LOGS_DIR"

echo "=============================================="
echo "Daily Scheduler - Silver Tier"
echo "=============================================="
echo "Date: $DATE"
echo "Time: $(date +%H:%M:%S)"
echo "Project Root: $PROJECT_ROOT"
echo "Done Directory: $DONE_DIR"
echo "Summary File: $SUMMARY_FILE"
echo "=============================================="
echo ""

# Check if Done directory exists and has files
if [ ! -d "$DONE_DIR" ]; then
    echo "Warning: Done directory does not exist: $DONE_DIR"
    mkdir -p "$DONE_DIR"
fi

# Count files in Done directory
FILE_COUNT=$(find "$DONE_DIR" -type f -name "*.md" 2>/dev/null | wc -l)
echo "Files in /Done/: $FILE_COUNT"
echo ""

# Generate daily summary
echo "Generating daily summary..."

cat > "$SUMMARY_FILE" << EOF
---
type: daily_summary
date: $DATE
generated: $(date -Iseconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S)
files_processed: $FILE_COUNT
status: complete
---

# Daily Summary - $DATE

## Overview

- **Generated:** $(date +%Y-%m-%d\ %H:%M:%S)
- **Files Processed:** $FILE_COUNT
- **Status:** Complete

## Files Completed Today

EOF

# List files modified today in Done directory
if [ "$FILE_COUNT" -gt 0 ]; then
    echo "### Recent Files" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
    echo "| File | Type | Modified |" >> "$SUMMARY_FILE"
    echo "|------|------|----------|" >> "$SUMMARY_FILE"
    
    find "$DONE_DIR" -type f -name "*.md" -mtime -1 2>/dev/null | while read -r file; do
        filename=$(basename "$file")
        # Try to extract type from file content
        file_type=$(grep -m1 "^type:" "$file" 2>/dev/null | cut -d: -f2 | tr -d ' ' || echo "unknown")
        [ -z "$file_type" ] && file_type="unknown"
        modified=$(stat -c %y "$file" 2>/dev/null | cut -d' ' -f1 || stat -f %sm "$file" 2>/dev/null | xargs -I{} date -r {} +%Y-%m-%d 2>/dev/null || echo "unknown")
        echo "| $filename | $file_type | $modified |" >> "$SUMMARY_FILE"
    done
    
    echo "" >> "$SUMMARY_FILE"
fi

# Add summary sections
cat >> "$SUMMARY_FILE" << EOF

## Activity Summary

### Tasks Completed
- Total files in /Done/: $FILE_COUNT

### Pending Actions
EOF

# Count pending items
PENDING_COUNT=$(find "$PROJECT_ROOT/Pending_Approval" -type f -name "*.md" 2>/dev/null | wc -l)
echo "- Pending Approval: $PENDING_COUNT" >> "$SUMMARY_FILE"

# Add notes section
cat >> "$SUMMARY_FILE" << EOF

## Notes

<!-- Add any additional notes or observations here -->

---
*Generated by Daily Scheduler - Silver Tier*
*Next run: Tomorrow at 8:00 AM*
EOF

echo "Summary created: $SUMMARY_FILE"
echo ""

# Log the run
LOG_ENTRY="[$(date +%Y-%m-%d\ %H:%M:%S)] Daily summary generated: $SUMMARY_FILE (files: $FILE_COUNT)"
echo "$LOG_ENTRY" >> "$LOGS_DIR/scheduler.log"

echo "=============================================="
echo "Schedule Complete"
echo "=============================================="
echo ""
echo "Next scheduled run: Tomorrow at 8:00 AM"
echo "Log file: $LOGS_DIR/scheduler.log"
echo ""

# Optional: Send notification (uncomment if you have notification setup)
# notify-send "Daily Summary Generated" "Completed $FILE_COUNT tasks today"

exit 0
