# Daily Scheduler - Silver Tier (Windows PowerShell)
# ===================================================
# Runs daily at 8AM to generate summary from /Done files
#
# Usage: .\daily_scheduler.ps1
#
# Setup (Windows Task Scheduler):
# --------------------------------
# 1. Open Task Scheduler (taskschd.msc)
# 2. Click "Create Basic Task" in right panel
# 3. Name: "AI Employee Daily Scheduler"
# 4. Trigger: Daily at 8:00 AM
# 5. Action: Start a program
#    - Program: powershell.exe
#    - Arguments: -ExecutionPolicy Bypass -File "D:\giaic\hackhathone_0\AI-Employee-Project\schedulers\daily_scheduler\daily_scheduler.ps1"
#    - Start in: D:\giaic\hackhathone_0\AI-Employee-Project\schedulers\daily_scheduler
# 6. Finish and test
#
# Test manually: .\daily_scheduler.ps1

# Configuration
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$DoneDir = Join-Path $ProjectRoot "Done"
$LogsDir = Join-Path $ProjectRoot "Logs"
$PendingDir = Join-Path $ProjectRoot "Pending_Approval"
$Date = Get-Date -Format "yyyy-MM-dd"
$Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$SummaryFile = Join-Path $LogsDir "daily_summary_$Date.md"

# Ensure logs directory exists
if (!(Test-Path $LogsDir)) {
    New-Item -ItemType Directory -Force -Path $LogsDir | Out-Null
}

Write-Host "=============================================="
Write-Host "Daily Scheduler - Silver Tier (Windows)"
Write-Host "=============================================="
Write-Host "Date: $Date"
Write-Host "Time: $(Get-Date -Format 'HH:mm:ss')"
Write-Host "Project Root: $ProjectRoot"
Write-Host "Done Directory: $DoneDir"
Write-Host "Summary File: $SummaryFile"
Write-Host "=============================================="
Write-Host ""

# Check if Done directory exists
if (!(Test-Path $DoneDir)) {
    Write-Host "Warning: Done directory does not exist: $DoneDir"
    New-Item -ItemType Directory -Force -Path $DoneDir | Out-Null
}

# Count files in Done directory
$FileCount = (Get-ChildItem -Path $DoneDir -Filter "*.md" -File 2>$null).Count
Write-Host "Files in /Done/: $FileCount"
Write-Host ""

# Generate daily summary
Write-Host "Generating daily summary..."

$SummaryContent = @"
---
type: daily_summary
date: $Date
generated: $(Get-Date -Format 'o')
files_processed: $FileCount
status: complete
---

# Daily Summary - $Date

## Overview

- **Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
- **Files Processed:** $FileCount
- **Status:** Complete

## Files Completed Today

"@

# List files modified today in Done directory
if ($FileCount -gt 0) {
    $SummaryContent += "`n### Recent Files`n`n"
    $SummaryContent += "| File | Type | Modified |`n"
    $SummaryContent += "|------|------|----------|`n"
    
    $Files = Get-ChildItem -Path $DoneDir -Filter "*.md" -File | Where-Object {
        $_.LastWriteTime -gt (Get-Date).AddDays(-1)
    }
    
    foreach ($File in $Files) {
        $Filename = $File.Name
        # Try to extract type from file content
        $Content = Get-Content $File.FullName -Raw
        $FileType = "unknown"
        if ($Content -match 'type:\s*(\w+)') {
            $FileType = $Matches[1]
        }
        $Modified = $File.LastWriteTime.ToString('yyyy-MM-dd')
        $SummaryContent += "| $Filename | $FileType | $Modified |`n"
    }
    
    $SummaryContent += "`n"
}

# Count pending items
$PendingCount = 0
if (Test-Path $PendingDir) {
    $PendingCount = (Get-ChildItem -Path $PendingDir -Filter "*.md" -File 2>$null).Count
}

# Add summary sections
$SummaryContent += @"

## Activity Summary

### Tasks Completed
- Total files in /Done/: $FileCount

### Pending Actions
- Pending Approval: $PendingCount

## Notes

<!-- Add any additional notes or observations here -->

---
*Generated by Daily Scheduler - Silver Tier*
*Next run: Tomorrow at 8:00 AM*
"@

# Write summary file
$SummaryContent | Out-File -FilePath $SummaryFile -Encoding UTF8

Write-Host "Summary created: $SummaryFile"
Write-Host ""

# Log the run
$LogEntry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] Daily summary generated: $SummaryFile (files: $FileCount)"
Add-Content -Path (Join-Path $LogsDir "scheduler.log") -Value $LogEntry

Write-Host "=============================================="
Write-Host "Schedule Complete"
Write-Host "=============================================="
Write-Host ""
Write-Host "Next scheduled run: Tomorrow at 8:00 AM"
Write-Host "Log file: $(Join-Path $LogsDir 'scheduler.log')"
Write-Host ""

# Optional: Show desktop notification (Windows 10+)
# [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] > $null
# [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] > $null
# $ToastXml = [Windows.Data.Xml.Dom.XmlDocument]::new()
# $ToastXml.LoadXml("<toast><visual><binding template='ToastText02'><text>Daily Summary</text><text>Completed $FileCount tasks today</text></binding></visual></toast>")
# $Toast = [Windows.UI.Notifications.ToastNotification]::new($ToastXml)
# [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("AI Employee").Show($Toast)

exit 0
