"""
WhatsApp Watcher - Silver Tier
==============================
Monitors WhatsApp Web for unread messages with specific keywords.

Keywords: urgent, invoice, payment, sales
Check Interval: 30 seconds
Output: Markdown files in /Needs_Action with YAML metadata

Setup Instructions:
-------------------
1. Install dependencies: pip install playwright
2. Install Playwright browsers: playwright install
3. First run will open browser for QR code scan (login to WhatsApp Web)
4. Session saved to /session/whatsapp for persistent login

Run with PM2:
-------------
pm2 start watchers/whatsapp_watcher.py --name "whatsapp-watcher" --interpreter python

Test:
-----
1. Run the script: python watchers/whatsapp_watcher.py
2. Scan QR code with WhatsApp mobile app (first time only)
3. Send yourself a WhatsApp message with "urgent" or "invoice"
4. Check /Needs_Action folder for generated .md file

Note: Requires browser window to remain open. For headless operation,
consider using WhatsApp Business API instead.
"""

import os
import sys
import time
import re
from datetime import datetime
from pathlib import Path

try:
    from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeout
except ImportError as e:
    print(f"Missing dependency: {e}")
    print("Install with: pip install playwright")
    print("Then run: playwright install")
    sys.exit(1)

# Configuration
KEYWORDS = ['urgent', 'invoice', 'payment', 'sales']
CHECK_INTERVAL = 30  # seconds
NEEDS_ACTION_DIR = Path(__file__).parent.parent / 'Needs_Action'
SESSION_PATH = Path(__file__).parent.parent / 'session' / 'whatsapp'
PROCESSED_MESSAGES_FILE = Path(__file__).parent.parent / 'watchers' / '.whatsapp_processed'

# Ensure directories exist
NEEDS_ACTION_DIR.mkdir(parents=True, exist_ok=True)
SESSION_PATH.mkdir(parents=True, exist_ok=True)

# Track processed message IDs to avoid duplicates
processed_messages = set()
if PROCESSED_MESSAGES_FILE.exists():
    with open(PROCESSED_MESSAGES_FILE, 'r') as f:
        processed_messages = set(f.read().strip().split('\n'))


def save_processed_message(msg_id):
    """Save processed message ID to avoid duplicates."""
    processed_messages.add(msg_id)
    with open(PROCESSED_MESSAGES_FILE, 'w') as f:
        f.write('\n'.join(processed_messages))


def contains_keyword(text, keywords):
    """Check if text contains any of the keywords (case-insensitive)."""
    text_lower = text.lower()
    return any(keyword.lower() in text_lower for keyword in keywords)


def get_priority(text):
    """Determine priority based on keywords."""
    text_lower = text.lower()
    if 'urgent' in text_lower:
        return 'high'
    elif 'invoice' in text_lower or 'payment' in text_lower:
        return 'medium'
    elif 'sales' in text_lower:
        return 'medium'
    return 'low'


def create_markdown_file(message_data):
    """Create markdown file with YAML metadata in Needs_Action folder."""
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    safe_sender = re.sub(r'[^\w\s-]', '', message_data['sender'])[:20]
    filename = f"whatsapp_{safe_sender}_{timestamp}.md"
    filepath = NEEDS_ACTION_DIR / filename
    
    content = f"""---
type: whatsapp_message
from: {message_data['sender']}
subject: {message_data['message'][:50]}
received: {message_data['received']}
priority: {message_data['priority']}
status: pending
keywords: {', '.join(message_data['matched_keywords'])}
message_id: {message_data['message_id']}
---

# WhatsApp Message

## Metadata
- **From:** {message_data['sender']}
- **Received:** {message_data['received']}
- **Priority:** {message_data['priority']}
- **Status:** {message_data['status']}
- **Matched Keywords:** {', '.join(message_data['matched_keywords'])}

## Content

{message_data['message']}

---
*Generated by WhatsApp Watcher - Silver Tier*
"""
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return filepath


def monitor_whatsapp():
    """Monitor WhatsApp Web for new messages with keywords."""
    with sync_playwright() as p:
        # Launch browser with persistent context
        browser = p.chromium.launch_persistent_context(
            user_data_dir=str(SESSION_PATH),
            headless=False,  # Keep visible for QR code scanning
            args=['--disable-blink-features=AutomationControlled']
        )
        
        page = browser.pages[0] if browser.pages else browser.new_page()
        
        print("[*] Navigating to WhatsApp Web...")
        page.goto('https://web.whatsapp.com', wait_until='networkidle')
        
        print("[*] Waiting for WhatsApp to load... (Scan QR code if prompted)")
        print("[*] Session will be saved for future runs")
        
        try:
            # Wait for chat list to appear (indicates successful login)
            page.wait_for_selector('div[role="navigation"]', timeout=60000)
            print("[*] WhatsApp Web loaded successfully!")
            print()
            
            while True:
                try:
                    # Find unread message indicators
                    # WhatsApp Web structure may change, adjust selectors as needed
                    unread_chats = page.query_selector_all('div[role="listitem"] span[aria-label*="unread"]')
                    
                    for chat in unread_chats:
                        try:
                            # Get chat info
                            chat_name_elem = chat.query_selector('span[title]')
                            if not chat_name_elem:
                                continue
                            
                            chat_name = chat_name_elem.get_attribute('title')
                            
                            # Click to open chat and read messages
                            chat.click()
                            time.sleep(1)  # Wait for messages to load
                            
                            # Get recent messages
                            message_elements = page.query_selector_all('div[role="listitem"] span[span]')
                            
                            for msg_elem in message_elements[-5:]:  # Last 5 messages
                                msg_text = msg_elem.inner_text()
                                
                                if not msg_text or msg_text.startswith('You:') or len(msg_text) < 2:
                                    continue
                                
                                # Create unique message ID
                                msg_id = f"{chat_name}_{msg_text[:20]}_{datetime.now().strftime('%H%M')}"
                                
                                if msg_id in processed_messages:
                                    continue
                                
                                # Check for keywords
                                if contains_keyword(msg_text, KEYWORDS):
                                    matched_keywords = [kw for kw in KEYWORDS if kw.lower() in msg_text.lower()]
                                    
                                    message_data = {
                                        'sender': chat_name,
                                        'message': msg_text,
                                        'received': datetime.now().isoformat(),
                                        'priority': get_priority(msg_text),
                                        'status': 'pending',
                                        'matched_keywords': matched_keywords,
                                        'message_id': msg_id
                                    }
                                    
                                    filepath = create_markdown_file(message_data)
                                    save_processed_message(msg_id)
                                    
                                    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] New message from {chat_name}")
                                    print(f"  - Keywords: {', '.join(matched_keywords)}")
                                    print(f"  - Priority: {message_data['priority']}")
                                    print(f"  - Saved: {filepath.name}")
                                    print()
                            
                            # Navigate back to chat list
                            back_button = page.query_selector('button[aria-label="Back"]')
                            if back_button:
                                back_button.click()
                                time.sleep(0.5)
                                
                        except Exception as e:
                            print(f"Error processing chat: {e}")
                            continue
                    
                    time.sleep(CHECK_INTERVAL)
                    
                except Exception as e:
                    print(f"Error during monitoring: {e}")
                    time.sleep(5)
                    
        except PlaywrightTimeout:
            print("[!] Timeout waiting for WhatsApp to load.")
            print("[*] Please scan QR code manually and restart the script.")
        finally:
            browser.close()


def main():
    """Main entry point for WhatsApp watcher."""
    print("=" * 60)
    print("WhatsApp Watcher - Silver Tier")
    print("=" * 60)
    print(f"Keywords: {', '.join(KEYWORDS)}")
    print(f"Check Interval: {CHECK_INTERVAL} seconds")
    print(f"Output Directory: {NEEDS_ACTION_DIR}")
    print(f"Session Path: {SESSION_PATH}")
    print("=" * 60)
    print("Starting watcher... (Press Ctrl+C to stop)")
    print()
    print("NOTE: A browser window will open. Scan QR code with WhatsApp mobile app.")
    print("      Keep browser window open for continuous monitoring.")
    print()
    
    try:
        monitor_whatsapp()
    except KeyboardInterrupt:
        print("\n\nWatcher stopped by user.")
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
